entitlement_test_wait_deployment: do not check openssl x509 -enddate if entitlement not deployed

diff --git a/roles/entitlement_test_wait_deployment/files/entitlement-tester_entrypoint.yml b/roles/entitlement_test_wait_deployment/files/entitlement-tester_entrypoint.yml
--- a/roles/entitlement_test_wait_deployment/files/entitlement-tester_entrypoint.yml
+++ b/roles/entitlement_test_wait_deployment/files/entitlement-tester_entrypoint.yml
@@ -73,13 +73,17 @@ data:
       fi
     done
 
-    # inspect the PEM certificate "notAfter" date
-    yum install -yq openssl
+    if [ -f /etc/pki/entitlement-host/entitlement.pem ]; then
+      # inspect the PEM certificate "notAfter" date
+      yum install -yq openssl
 
-    EXPIRATION_WARNING_DELAY_HR=48
-    openssl x509 -enddate -noout -in /etc/pki/entitlement-host/entitlement.pem # prints the `notAfter` date
-    if ! openssl x509 -checkend $(($EXPIRATION_WARNING_DELAY_HR * 60 * 60)) -noout -in /etc/pki/entitlement-host/entitlement.pem; then
-      echo "WARNING: PEM certificate expires in less than ${EXPIRATION_WARNING_DELAY_HR} hours ..."
+      EXPIRATION_WARNING_DELAY_HR=48
+      openssl x509 -enddate -noout -in /etc/pki/entitlement-host/entitlement.pem # prints the `notAfter` date
+      if ! openssl x509 -checkend $(($EXPIRATION_WARNING_DELAY_HR * 60 * 60)) -noout -in /etc/pki/entitlement-host/entitlement.pem; then
+        echo "WARNING: PEM certificate expires in less than ${EXPIRATION_WARNING_DELAY_HR} hours ..."
+      fi
+    else
+      echo "Entitlement file not found, cannot check its expiration date."
     fi
 
     echo
