WIP / hack: wait 30 minutes for warmup and then continue

diff --git a/roles/wisdom/wisdom_warmup_model/tasks/main.yml b/roles/wisdom/wisdom_warmup_model/tasks/main.yml
--- a/roles/wisdom/wisdom_warmup_model/tasks/main.yml
+++ b/roles/wisdom/wisdom_warmup_model/tasks/main.yml
@@ -36,32 +36,36 @@
 - name: Create the wisdom warmup Pod if it exists
   command: oc create -f "{{ artifact_extra_logs_dir }}/src/000_wisdom_warmup_pod.yml" -n {{ wisdom_warmup_model_namespace }}
 
+- name: Pause for 30 minutes to wait for all Pods to load and pt2_compile
+  ansible.builtin.pause:
+    minutes: 30
+
 # Wait for wisdom modelmesh Pods to all load the model.
-- name: Wait for wisdom model mesh Pods to be ready
-  block:
-  # Iterate through each modelmesh Pod and verify that the model is taking up more space than 0 GB.
-  # This means that it is loading/loaded.
-  - name: Ensure that wisdom model mesh deployment is ready
-    shell: |
-      set -o errexit
-      set -o pipefail
-      set -o nounset
-      set -o errtrace
-      set -x
-      for pod in $(oc get pod -oname -n {{ wisdom_warmup_model_namespace }}  | grep 'modelmesh-serving'); do
-          if ! oc logs -n {{ wisdom_warmup_model_namespace }}  $pod -c runtime | grep -q 'Successfully loaded'; then
-            if ! oc logs -n {{ wisdom_warmup_model_namespace }}  $pod -c runtime | grep -q 'Request generated'; then
-              echo "At least one wisdom Pod ($pod) still hasn't loaded the model"
-              exit 1
-            fi
-          fi
-      done
-    register: model_loaded
-    until:
-    - model_loaded.rc == 0
-    - not model_loaded.stdout
-    retries: 40
-    delay: 60
+#- name: Wait for wisdom model mesh Pods to be ready
+#  block:
+#  # Iterate through each modelmesh Pod and verify that the model is taking up more space than 0 GB.
+#  # This means that it is loading/loaded.
+#  - name: Ensure that wisdom model mesh deployment is ready
+#    shell: |
+#      set -o errexit
+#      set -o pipefail
+#      set -o nounset
+#      set -o errtrace
+#      set -x
+#      for pod in $(oc get pod -oname -n {{ wisdom_warmup_model_namespace }}  | grep 'modelmesh-serving'); do
+#          if ! oc logs -n {{ wisdom_warmup_model_namespace }}  $pod -c runtime | grep -q 'Successfully loaded'; then
+#            if ! oc logs -n {{ wisdom_warmup_model_namespace }}  $pod -c runtime | grep -q 'Request generated'; then
+#              echo "At least one wisdom Pod ($pod) still hasn't loaded the model"
+#              exit 1
+#            fi
+#          fi
+#      done
+#    register: model_loaded
+#    until:
+#    - model_loaded.rc == 0
+#    - not model_loaded.stdout
+#    retries: 40
+#    delay: 60
 
 - name: Delete the wisdom warmup Pod if it exists
   command: oc delete  --ignore-not-found=true -f "{{ artifact_extra_logs_dir }}/src/000_wisdom_warmup_pod.yml" -n {{ wisdom_warmup_model_namespace }}
