Add SRO to ci-artifacts, and rebase run to support libraries for multiple operators.

diff --git a/build/root/usr/local/bin/run b/build/root/usr/local/bin/run
--- a/build/root/usr/local/bin/run
+++ b/build/root/usr/local/bin/run
@@ -53,6 +53,16 @@ prechecks() {
         cd ..
     fi
 
+    if ! which kubectl &>/dev/null;
+    then
+        echo "kubectl not found, symlinking to oc"
+        mkdir -p bin
+        cd bin
+        ln -s $(which oc) kubectl
+        export PATH=$PWD:$PATH
+        cd ..
+    fi
+
     if ! which helm &>/dev/null;
     then
         echo "Helm not found, downloading it ..."
@@ -86,51 +96,7 @@ prechecks() {
     fi
 }
 
-entitle() {
-    echo "Testing if the cluster is already entitled ..."
-    if toolbox/entitlement/test.sh --no-inspect; then
-        echo "Cluster already entitled, skipping entitlement."
-        return
-    fi
 
-    entitlement_deployed=0
-
-    ENTITLEMENT_PEM=${ENTITLEMENT_PEM:-/var/run/psap-entitlement-secret/entitlement.pem}
-    if [ -z "$ENTITLEMENT_PEM" ]; then
-        echo "INFO: no entitlement key provided (ENTITLEMENT_PEM)"
-    elif [ ! -e "$ENTITLEMENT_PEM" ]; then
-        echo "INFO: entitlement key doesn't exist (ENTITLEMENT_PEM=$ENTITLEMENT_PEM)"
-    else
-        echo "Deploying the entitlement with PEM key from ${ENTITLEMENT_PEM}"
-        toolbox/entitlement/deploy.sh --pem ${ENTITLEMENT_PEM}
-        entitlement_deployed=1
-    fi
-
-    ENTITLEMENT_RESOURCES=${ENTITLEMENT_RESOURCES:-/var/run/psap-entitlement-secret/01-cluster-wide-machineconfigs.yaml}
-    if [ "$entitlement_deployed" == 1 ]; then
-        # entitlement already deployed
-        true
-    elif [ -z "$ENTITLEMENT_RESOURCES" ]; then
-        echo "INFO: no entitlement resource provided (ENTITLEMENT_RESOURCES)"
-    elif [ ! -e "$ENTITLEMENT_RESOURCES" ]; then
-        echo "INFO: entitlement resource file doesn't exist (ENTITLEMENT_RESOURCES=$ENTITLEMENT_RESOURCES)"
-     else
-        echo "Deploying the entitlement from resources inside ${ENTITLEMENT_RESOURCES}"
-        toolbox/entitlement/deploy.sh --machine-configs ${ENTITLEMENT_RESOURCES}
-        entitlement_deployed=1
-    fi
-
-
-    if [ "$entitlement_deployed" == 0 ]; then
-        echo "FATAL: cluster isn't entitled and not entitlement provided (ENTITLEMENT_PEM)"
-        exit 1
-    fi
-
-    if ! toolbox/entitlement/wait.sh; then
-        echo "FATAL: Failed to properly entitle the cluster, cannot continue."
-        exit 1
-    fi
-}
 
 ##############
 
@@ -145,91 +111,24 @@ else
     echo "Using '$ARTIFACT_DIR' to store the test artifacts"
 fi
 
-prepare_cluster_for_gpu_operator() {
-    toolbox/cluster/capture_environment.sh
 
-    entitle
-
-    if ! toolbox/nfd/has_nfd_labels.sh; then
-        toolbox/nfd/deploy_from_operatorhub.sh
-    fi
-
-    if ! toolbox/nfd/has_gpu_nodes.sh; then
-        toolbox/cluster/scaleup.sh
-        toolbox/nfd/wait_gpu_nodes.sh
-    fi
-}
-
-collect_must_gather() {
-    /usr/bin/gather
-    DEST="${ARTIFACT_DIR}/$(date +%H%M%S)__gpu-operator__must-gather"
-    mkdir -p "$DEST"
-    cp -r /must-gather/* "$DEST"
-}
-
-validate_gpu_operator_deployment() {
-    trap collect_must_gather ERR
-
-    toolbox/gpu-operator/wait_deployment.sh
-    toolbox/gpu-operator/run_gpu_burn.sh
-
-    trap - ERR
-
-    collect_must_gather
-}
+script_name="$0"
+target="$1"
+action="$2"
+shift 2
 
 set -x
-case ${1:-} in
-    "gpu-operator_test-master-branch")
-        prepare_cluster_for_gpu_operator
-        toolbox/gpu-operator/deploy_from_operatorhub.sh --from-bundle=master
 
-        validate_gpu_operator_deployment
-        exit 0
+export ENTRY_LIB_DIR="/var/lib/ci-artifacts/entrypoints.d"
+case ${target:-} in
+    "gpu-operator")
+        $ENTRY_LIB_DIR/gpu_operator_run_libs.sh $action "$@"
+	exit 0
         ;;
-    "gpu-operator_test-commit")
-        CI_IMAGE_GPU_COMMIT_CI_REPO="${2:-https://github.com/NVIDIA/gpu-operator.git}"
-        CI_IMAGE_GPU_COMMIT_CI_REF="${3:-master}"
-
-        CI_IMAGE_GPU_COMMIT_CI_IMAGE_UID="ci-image"
-
-        echo "Using Git repository ${CI_IMAGE_GPU_COMMIT_CI_REPO} with ref ${CI_IMAGE_GPU_COMMIT_CI_REF}"
-
-        prepare_cluster_for_gpu_operator
-        toolbox/gpu-operator/deploy_from_commit.sh "${CI_IMAGE_GPU_COMMIT_CI_REPO}" \
-                                                   "${CI_IMAGE_GPU_COMMIT_CI_REF}" \
-                                                   "${CI_IMAGE_GPU_COMMIT_CI_IMAGE_UID}"
-        validate_gpu_operator_deployment
-        exit 0
+    "sro")
+        $ENTRY_LIB_DIR/sro_run_libs.sh $action "$@"
+	exit 0
         ;;
-    "gpu-operator_test-operatorhub")
-        OPERATOR_VERSION="${2:-}"
-        prepare_cluster_for_gpu_operator
-        toolbox/gpu-operator/deploy_from_operatorhub.sh ${OPERATOR_VERSION}
-        validate_gpu_operator_deployment
-        exit 0
-        ;;
-    "gpu-operator_validate-deployment")
-        validate_gpu_operator_deployment
-        exit 0
-        ;;
-    "gpu-operator_test-helm")
-        if [ -z "${2:-}" ]; then
-            echo "FATAL: $0 $1 should receive the operator version as parameter."
-            exit 1
-        fi
-        OPERATOR_VERSION="$2"
-
-        prepare_cluster_for_gpu_operator
-        toolbox/gpu-operator/list_version_from_helm.sh
-        toolbox/gpu-operator/deploy_with_helm.sh ${OPERATOR_VERSION}
-        validate_gpu_operator_deployment
-        exit 0
-        ;;
-    "gpu-operator_undeploy-operatorhub")
-        toolbox/gpu-operator/undeploy_from_operatorhub.sh
-        exit 0
-	;;
     "cluster-upgrade")
         if [ -z "${CLUSTER_UPGRADE_TARGET_IMAGE:-}" ]; then
             echo "FATAL: CLUSTER_UPGRADE_TARGET_IMAGE must be provided to upgrade the cluster"
@@ -239,7 +138,7 @@ case ${1:-} in
         exit 0
         ;;
     -*)
-        echo "Unknown option: ${1:-}"
+        echo "Unknown option: ${target:-}"
         exit 1
         ;;
 
