gpu_operator_bundle_from_commit: add --publish_to_quay --with_driver --with_validator flags

diff --git a/roles/gpu_operator_bundle_from_commit/files/operator_bundle_image_builder_script.yml b/roles/gpu_operator_bundle_from_commit/files/operator_bundle_image_builder_script.yml
--- a/roles/gpu_operator_bundle_from_commit/files/operator_bundle_image_builder_script.yml
+++ b/roles/gpu_operator_bundle_from_commit/files/operator_bundle_image_builder_script.yml
@@ -13,19 +13,44 @@ data:
     set -o nounset
     set -x
 
-    echo "QUAY_BUNDLE_IMAGE_NAME=${QUAY_BUNDLE_IMAGE_NAME}"
-    echo "OPERATOR_IMAGE_NAME=${OPERATOR_IMAGE_NAME}"
+    LOCAL_OPERATOR_IMAGE_REPOSITORY="image-registry.openshift-image-registry.svc:5000/gpu-operator-ci"
+    LOCAL_OPERATOR_IMAGE_NAME="gpu-operator-ci"
 
-    CONTAINER_FILE=./bundle.Dockerfile
-    if [ ! -f ${CONTAINER_FILE} ]; then
-      # TODO: This branch allows for bundles to be built for the modified GPU operator make file.
-      # This was merged in https://github.com/NVIDIA/gpu-operator/commit/b0e99d9e6ac8738ee335f6e866242b1c9977ea09
-      # This can be set as the default once no older versions are built.
-      CONTAINER_FILE=./docker/bundle.Dockerfile
+    echo "QUAY_BUNDLE_IMAGE_NAME=${QUAY_BUNDLE_IMAGE_NAME}"
+
+    if [ "${PUBLISH_TO_QUAY:-}" ]; then
+      if [ "${WITH_DRIVER:-}" ]; then
+        echo "FATAL: Cannot have PUBLISH_TO_QUAY and WITH_DRIVER enabled together."
+        exit 1
+      fi
+
+      OPERATOR_IMAGE_REPOSITORY="$(dirname "$QUAY_BUNDLE_IMAGE_NAME")"
+      OPERATOR_IMAGE_NAME="$(basename "$QUAY_BUNDLE_IMAGE_NAME")"
+    else
+      OPERATOR_IMAGE_REPOSITORY="${LOCAL_OPERATOR_IMAGE_REPOSITORY}"
+      OPERATOR_IMAGE_NAME="${LOCAL_OPERATOR_IMAGE_NAME}"
     fi
+
+    OPERATOR_IMAGE_VERSION="operator_${OPERATOR_IMAGES_TAG_SUFFIX}"
+
+    OPERATOR_IMAGE_FULL="${OPERATOR_IMAGE_REPOSITORY}/${OPERATOR_IMAGE_NAME}:${OPERATOR_IMAGE_VERSION}"
+    BUNDLE_IMAGE_FULL="${QUAY_BUNDLE_IMAGE_NAME}:operator_bundle_${OPERATOR_IMAGES_TAG_SUFFIX}"
+
+    TAGS_TO_PUSH_TO_QUAY="${OPERATOR_IMAGE_VERSION}"
+
+    CONTAINER_FILE=./docker/bundle.Dockerfile
+
     CONTEXT_LOCATION="."
 
     CSV_FILE=bundle/manifests/gpu-operator.clusterserviceversion.yaml
+
+    (echo "{ \"auths\": " ; cat /var/run/secrets/openshift.io/push/.dockercfg ; echo "}") > /tmp/.dockercfg_local
+    LOCAL_AUTH="--tls-verify=false --authfile /tmp/.dockercfg_local"
+
+    cat /var/run/secrets/quay.io/push/.dockerconfigjson > /tmp/.dockercfg_quay
+    QUAY_AUTH="--tls-verify=false --authfile /tmp/.dockercfg_quay"
+
+    # ---
 
     mkdir /work && cd /work
 
@@ -39,32 +64,56 @@ data:
     DATE_VERSION=$(date -d "@$(git log -1 ${GIT_VERSION} --format="%at")" +%y.%-m.%-d) # gives 21.9.29
     CSV_VERSION="${DATE_VERSION}-git.${GIT_VERSION}"
 
-    # update operator image
-    mv $CSV_FILE ${CSV_FILE}.orig
-    cat ${CSV_FILE}.orig | yq \
-      | jq .metadata.annotations.containerImage=\"${OPERATOR_IMAGE_NAME}\" \
-      | jq .metadata.name=\"gpu-operator-certified-${CSV_VERSION}\" \
-      | jq .spec.version=\"${CSV_VERSION}\" \
-      | jq .spec.install.spec.deployments[0].spec.template.spec.containers[0].image=\"$OPERATOR_IMAGE_NAME\" \
+    cp "$CSV_FILE" "${CSV_FILE}.orig"
+
+    cat "${CSV_FILE}.orig" | yq \
+      | jq '.metadata.annotations.containerImage="'${OPERATOR_IMAGE_FULL}'"' \
+      | jq '.metadata.name="'gpu-operator-certified-${CSV_VERSION}'"' \
+      | jq '.spec.version="'${CSV_VERSION}'"' \
+      | jq '.spec.install.spec.deployments[0].spec.template.spec.containers[0].image="'$OPERATOR_IMAGE_FULL'"' \
       > $CSV_FILE
 
     rm ${CSV_FILE}.orig
 
-    # update validator & node-status-exporter images in the ClusterPolicy
-
     cat ${CSV_FILE} | yq \
       | jq '.metadata.annotations."alm-examples"' -r \
-      > clusterpolicy.json.orig
+        > clusterpolicy.json
 
-    cat clusterpolicy.json.orig \
-      | jq '.[].spec.validator.image="gpu-operator-ci"' \
-      | jq '.[].spec.validator.repository="image-registry.openshift-image-registry.svc:5000/gpu-operator-ci"' \
-      | jq '.[].spec.validator.version="'${VALIDATOR_IMAGE_VERSION}'"' \
-      | jq '.[].spec.nodeStatusExporter.image="gpu-operator-ci"' \
-      | jq '.[].spec.nodeStatusExporter.repository="image-registry.openshift-image-registry.svc:5000/gpu-operator-ci"' \
-      | jq '.[].spec.nodeStatusExporter.version="'${VALIDATOR_IMAGE_VERSION}'"' \
-      > clusterpolicy.json
-    rm  clusterpolicy.json.orig
+    if [ "${WITH_VALIDATOR:-}" ]; then
+      # update validator & node-status-exporter images in the ClusterPolicy
+      VALIDATOR_IMAGE_VERSION="validator_${OPERATOR_IMAGES_TAG_SUFFIX}"
+
+      TAGS_TO_PUSH_TO_QUAY="${TAGS_TO_PUSH_TO_QUAY} ${VALIDATOR_IMAGE_VERSION}"
+
+      mv clusterpolicy.json{,.orig}
+      cat clusterpolicy.json.orig \
+        | jq '.[].spec.validator.image="'${OPERATOR_IMAGE_NAME}'"' \
+        | jq '.[].spec.validator.repository="'${OPERATOR_IMAGE_REPOSITORY}'"' \
+        | jq '.[].spec.validator.version="'${VALIDATOR_IMAGE_VERSION}'"' \
+        \
+        | jq '.[].spec.nodeStatusExporter.image="'${OPERATOR_IMAGE_NAME}'"' \
+        | jq '.[].spec.nodeStatusExporter.repository="'${OPERATOR_IMAGE_REPOSITORY}'"' \
+        | jq '.[].spec.nodeStatusExporter.version="'${VALIDATOR_IMAGE_VERSION}'"' \
+        > clusterpolicy.json
+
+      rm  clusterpolicy.json.orig
+    fi
+
+    if [ "${WITH_DRIVER:-}" ]; then
+      # update vdriver image in the ClusterPolicy
+      img="${OPERATOR_IMAGE_REPOSITORY}/${OPERATOR_IMAGE_NAME}:driver_${OPERATOR_IMAGES_TAG_SUFFIX}"
+      podman pull --quiet $LOCAL_AUTH "$img"
+      DRIVER_IMAGE_VERSION="$(podman inspect "$img" | jq -r .[].Digest)"
+
+      mv clusterpolicy.json{,.orig}
+
+      cat clusterpolicy.json.orig \
+        | jq '.[].spec.driver.image="'${OPERATOR_IMAGE_NAME}'"' \
+        | jq '.[].spec.driver.repository="'${OPERATOR_IMAGE_REPOSITORY}'"' \
+        | jq '.[].spec.driver.version="'${DRIVER_IMAGE_VERSION}'"' \
+        > clusterpolicy.json
+      rm  clusterpolicy.json.orig
+    fi
 
     # update ClusterPolicy in the CSV
 
@@ -75,11 +124,21 @@ data:
 
     # build the bundle image
 
-    podman build -f "${CONTAINER_FILE}" "${CONTEXT_LOCATION}" -t "${QUAY_BUNDLE_IMAGE_NAME}"
+    podman build -f "${CONTAINER_FILE}" "${CONTEXT_LOCATION}" -t "${BUNDLE_IMAGE_FULL}"
 
-    # push the image to quay.io
+    # push the bundle image to quay.io
 
-    cat /var/run/secrets/openshift.io/push/.dockerconfigjson > /tmp/.dockercfg
-    AUTH="--tls-verify=false --authfile /tmp/.dockercfg"
+    # mandatory for now, the bundle image must be accessible from the whole cluster
+    # I couldn't find any way not involving storing the bundle image in quay.io
 
-    podman push $AUTH "$QUAY_BUNDLE_IMAGE_NAME"
+    podman push $QUAY_AUTH "${BUNDLE_IMAGE_FULL}"
+
+    if [ "${PUBLISH_TO_QUAY:-}" ]; then
+      for tag in ${TAGS_TO_PUSH_TO_QUAY}; do
+        local_img="${LOCAL_OPERATOR_IMAGE_REPOSITORY}/${LOCAL_OPERATOR_IMAGE_NAME}:${tag}"
+        # pull the images locally
+        podman pull --quiet $LOCAL_AUTH "$local_img"
+        # then push it to quay
+        podman push --quiet $QUAY_AUTH "$local_img" "${QUAY_BUNDLE_IMAGE_NAME}:${tag}"
+      done
+    fi
