codeflare_generate_mcad_load: add target_states and fail_if_states

diff --git a/roles/codeflare_generate_mcad_load/tasks/main.yml b/roles/codeflare_generate_mcad_load/tasks/main.yml
--- a/roles/codeflare_generate_mcad_load/tasks/main.yml
+++ b/roles/codeflare_generate_mcad_load/tasks/main.yml
@@ -27,23 +27,41 @@
     shell:
       python3 "{{ mcad_load_generator }}" "{{ codeflare_generate_mcad_load_namespace }}" --dry-run=False
 
+  - name: Define the variables
+    set_fact:
+      success_states: "{{ codeflare_generate_mcad_load_target_states | map('to_json') | join(', ') }}"
+      failed_states: "{{ codeflare_generate_mcad_load_fail_if_states | map('to_json') | join(', ') }}"
+
   - name: Wait for the AppWrappers to complete
-    shell:
-      set -o pipefail;
-      oc get appwrappers -n {{ codeflare_generate_mcad_load_namespace }} -ojson
-        | jq '(.items | length) - ([.items[] | select(.status.state == "Completed")] | length)'
-    register: appwrappers_not_completed
+    shell: |
+      set -o pipefail; set -e;
+      appwrappers_json=$(oc get appwrappers -n {{ codeflare_generate_mcad_load_namespace }} -ojson)
+
+      jq '.items[] | .metadata.name + " ==> "+ .status.state' -r <<< $appwrappers_json
+
+      appwrapper_count=$(jq '.items | length' <<< $appwrappers_json)
+      appwrapper_successes=$(jq '[.items[] | select(.status.state | IN({{ success_states }}))] | length' <<< $appwrappers_json)
+      appwrapper_failed=$(jq '[.items[] | select(.status.state | IN({{ failed_states }}))] | length' <<< $appwrappers_json)
+
+      if [[ "$appwrapper_failed" != 0 ]]; then
+        echo "Found $appwrapper_failed AppWrapper(s) in one of the unexpected states '{{ failed_states }}' , aborting."
+        exit 1 # fatal
+      fi
+
+      if [[ "$appwrapper_count" != "$appwrapper_successes" ]]; then
+         echo "Only $appwrapper_successes/$appwrapper_count AppWrappers are in the expected states '{{ success_states }}'. Continue waiting ...."
+         exit 2 # retry
+      fi
+
+      echo "All the AppWrappers have completed successfully. All done."
+      exit 0 # done
+    register: appwrappers_completed
     retries: 60
     delay: 30
-    until: appwrappers_not_completed.stdout == "0"
-
-  - name: Count the number of completed AppWrappers, fail if zero
-    shell:
-      set -o pipefail;
-      oc get appwrappers -n {{ codeflare_generate_mcad_load_namespace }} -ojson
-        | jq '[.items[] | select(.status.state == "Completed")] | length'
-    register: appwrappers_completed
-    failed_when: appwrappers_completed.stdout == "0"
+    # until fatal or done
+    until: appwrappers_completed.rc == 1 or appwrappers_completed.rc == 0
+    # failed when fatal
+    failed_when: appwrappers_completed.rc == 1
 
   always:
   - name: Capture the state of the AppWrappers
