testing: run: improve the prechecks
So that 'run' does not fail when running in a container but outside of a CI

diff --git a/testing/run b/testing/run
--- a/testing/run
+++ b/testing/run
@@ -27,9 +27,14 @@ ci_banner() {
 
 prechecks() {
     if [ -z "${ARTIFACT_DIR:-}" ]; then
-        if [[ "${INSIDE_CI_IMAGE:-}" == "y" ]]; then
-            echo "ARTIFACT_DIR not set, cannot proceed without inside the image."
-            false
+        if [[ "${OPENSHIFT_CI:-}" == true ]]; then
+            echo "ARTIFACT_DIR not set, cannot proceed without it in OpenShift CI."
+            exit 1
+        elif [[ "${PERFLAB_CI:-}" == true ]]; then
+            echo "ARTIFACT_DIR not set, cannot proceed without it in PerfLab CI."
+            exit 1
+        else
+            echo "ARTIFACT_DIR not set, but not running in a CI. Creating a directory for it ..."
         fi
 
         export ARTIFACT_DIR="/tmp/ci-artifacts_$(date +%Y%m%d)"
