testing: run: do not run if $ARTIFACT_DIR/FAILURES already exists
This file is used to determine in postchecks() to know if the test failed or not

diff --git a/testing/run b/testing/run
--- a/testing/run
+++ b/testing/run
@@ -28,6 +28,11 @@ ci_banner() {
 }
 
 prechecks() {
+    if [ -e "$ARTIFACT_DIR/FAILURES" ]; then
+        echo "File '$ARTIFACT_DIR/FAILURES' already exists, cannot continue."
+        exit 1
+    fi
+
     if [ -z "${ARTIFACT_DIR:-}" ]; then
         if [[ "${INSIDE_CI_IMAGE:-}" == "y" ]]; then
             echo "ARTIFACT_DIR not set, cannot proceed without inside the image."
