local_ci_run_multi: integrate StateSignal startup synchronization

diff --git a/roles/local_ci_run_multi/templates/job.yaml.j2 b/roles/local_ci_run_multi/templates/job.yaml.j2
--- a/roles/local_ci_run_multi/templates/job.yaml.j2
+++ b/roles/local_ci_run_multi/templates/job.yaml.j2
@@ -45,6 +45,31 @@ spec:
           EOF
 {% endif %}
 
+{% if local_ci_run_multi_state_signal_redis_server %}
+          # Use StateSignal-barrier to wait for all the Pods to be ready
+          echo "Running with user $JOB_COMPLETION_INDEX / $USER_COUNT"
+          STATE_SIGNAL_DELAY=-1 # delay for all the Pods to reach the entry barrier
+          if [[ $JOB_COMPLETION_INDEX == 0 ]]; then
+              python3 "$STATE_SIGNAL_BARRIER" "$REDIS_SERVER" \
+                      --exporter "$USER_COUNT" \
+                      --delay "$STATE_SIGNAL_DELAY" &
+          fi
+
+          echo "statesignal_setup: $(date)" >> "${ARTIFACT_DIR}/progress_ts.yaml"
+          if ! python3 "$STATE_SIGNAL_BARRIER" "$REDIS_SERVER"; then
+              # fails if the all Pods don't reach the barrier in time
+              echo "StateSignal syncrhonization failed :( (errcode=$?)"
+
+              # mark this test as failed
+              echo 1 > "$ARTIFACT_DIR/test.exit_code"
+
+              # exit the Pod successfully, so that all the Pod logs are retrieved.
+              # without this, we don't know why the 'fail' event was generated.
+              exit 0
+          fi
+          echo "statesignal_ready: $(date)" >> "${ARTIFACT_DIR}/progress_ts.yaml"
+{% endif %}
+
           bash -x /opt/ci-artifacts/src/testing/run {{ local_ci_run_multi_ci_command }} |& tee "${ARTIFACT_DIR}/run.log"
         image: "image-registry.openshift-image-registry.svc:5000/{{ local_ci_run_multi_namespace }}/{{ local_ci_run_multi_istag }}"
         imagePullPolicy: Always
@@ -66,6 +91,14 @@ spec:
 {% endif %}
         - name: SHARED_DIR # shouldn't be used
           value: /tmp/shared
+        - name: USER_COUNT
+          value: "{{ local_ci_run_multi_user_count }}"
+{% if local_ci_run_multi_state_signal_redis_server %}
+        - name: STATE_SIGNAL_BARRIER
+          value: subprojects/state-signal-utils/state-signal_barrier.py
+        - name: REDIS_SERVER
+          value: "{{ local_ci_run_multi_state_signal_redis_server }}"
+{% endif %}
         volumeMounts:
         - mountPath: /logs
           name: artifacts
