watsonx_serving_deploy_model: update to use the latest design for the serving runtime

diff --git a/roles/watsonx_serving/watsonx_serving_deploy_model/tasks/main.yml b/roles/watsonx_serving/watsonx_serving_deploy_model/tasks/main.yml
--- a/roles/watsonx_serving/watsonx_serving_deploy_model/tasks/main.yml
+++ b/roles/watsonx_serving/watsonx_serving_deploy_model/tasks/main.yml
@@ -116,11 +116,28 @@
 
 # Serving Runtime
 
+- name: Prepare the caikit-tgis-config template
+  template:
+    src: "{{ caikit_tgit_config_template }}"
+    dest: "{{ artifact_extra_logs_dir }}/src/caikit_tgit_config.yaml"
+    mode: '0400'
+
 - name: Prepare the ServingRuntime template
   template:
     src: "{{ serving_runtime_template }}"
     dest: "{{ artifact_extra_logs_dir }}/src/serving_runtime.yaml"
     mode: '0400'
+
+- name: Create or update the Caikit TGIS config
+  shell:
+    set -o pipefail;
+
+    oc create cm {{ watsonx_serving_deploy_model_serving_runtime_name }}-caikit-tgis-config
+       -n {{ watsonx_serving_deploy_model_namespace }}
+       --from-file=caikit.yml="{{ artifact_extra_logs_dir }}/src/caikit_tgit_config.yaml"
+       --dry-run=client
+       -oyaml
+       | oc apply -f-
 
 - name: Create the ServingRuntime
   command:
@@ -178,9 +195,39 @@
       -n {{ watsonx_serving_deploy_model_namespace }}
     register: inference_service_pod_fetching_cmd
     # wait 60 minutes
-    retries: 60
-    delay: 60
+    retries: 120
+    delay: 30
     until: inference_service_pod_fetching_cmd.stdout | length > 0
+
+  - name: Wait for all the containers to be ready
+    shell: |
+      set -o pipefail;
+      set -e;
+
+      status=$(oc get pod \
+        -ojson \
+        -lserving.kserve.io/inferenceservice={{ watsonx_serving_deploy_model_inference_service_name }} \
+        -n {{ watsonx_serving_deploy_model_namespace }} \
+        | jq -r '.items[0].status.containerStatuses[] | ("" + .name +" ready="+ (.ready|tostring)) +" restarted="+(.restartCount|tostring)')
+      echo "$status"
+
+      if grep -v restarted=0 <<< $status >&2; then
+        echo "Restart detected, aborting" >&2
+        exit 2
+      fi
+
+      if grep -v ready=true <<< $status >&2; then
+        echo "Containers not ready detected, keep waiting ..." >&2
+        exit 1
+      fi
+
+      echo "All the containers are ready, all good :)" >&2
+    register: inference_service_pod_ready
+    failed_when: inference_service_pod_ready.rc == 2
+    until: inference_service_pod_ready.rc == 0 or inference_service_pod_ready.rc == 2
+    # wait 90 minutes
+    retries: 180
+    delay: 30
 
   - name: Wait for the InferenceService Pod to initialize the model
     shell:
@@ -188,9 +235,9 @@
       oc get -f "{{ artifact_extra_logs_dir }}/src/inference_service.yaml"
          -ojsonpath={.status.modelStatus.states.targetModelState}
     register: inference_service_state_cmd
-    # wait 90 minutes
-    retries: 180
-    delay: 30
+    # wait 5 minutes
+    retries: 30
+    delay: 10
     until: inference_service_state_cmd.stdout == "Loaded"
 
   - name: Capture the state of the InferenceService Pod resource
